name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm i .
    - name: Style check
      run: npm run lint
    - name: Run tests and make coverage
      run: npm run coverage
    - name: Send test coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.info
